---
PACKAGES     : [default-jdk, maven, git]
GIT_REPO     : https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
GIT_DIR      : /root/git
PATH_TARGET  : "{{GIT_DIR}}/target"
FILE_TARGET  : "hello-1.0.war"
REMOTE_USER  : ubuntu
ssh_private_key   : ./aws___key_pair_rsa_1_.pem
