---
- name: Create AWS_EC2 instance Building
  hosts: LOCAL
  connection: local
  gather_facts: yes
  tasks:
    - name: Add inventory Build.
      ansible.builtin.add_host:
        hosts: BUILD
        ansible_ssh_private_key_file: '{{ ssh_private_key  }}'
    - name: Wait.
      ansible.builtin.wait_for:
        hosts: BUILD
        port: 22
        state: started
    - name: Add inventory Prod.
      ansible.builtin.add_host:
        hosts: PROD
        ansible_ssh_private_key_file: '{{ ssh_private_key  }}'
    - name: Wait.
      ansible.builtin.wait_for:
        hosts: PROD
        port: 22
        state: started

- name: Build stage.
  hosts: BUILD
  remote_user: '{{ REMOTE_USER  }}'
  become: yes
  tasks:
  - command: apt update
  - name: Install packages.
    apt: name={{item}} state=present
    with_items: "{{PACKAGES}}"
  - name: GIT clone.
    git: repo='{{GIT_REPO}}' dest='{{GIT_DIR}}'
  - name: Build-app.
    command: chdir='{{GIT_DIR}}' mvn package
  - name: Copy .war file.
    fetch: src="{{PATH_TARGET}}/{{FILE_TARGET}}" dest="/tmp/{{FILE_TARGET}}" flat=true

- name: Prod stage.
  hosts: PROD
  remote_user: '{{ REMOTE_USER  }}'
  become: yes
  tasks:
  - command: apt update
  - name: Install java & tomcat9.
    apt: name={{item}} state=present
    with_items: "{{PACKAGES}}"
  - name: Status tomcat
    service: name=tomcat9 state=started
  - name: Copy .war file.
    copy: src="/tmp/{{FILE_TARGET}}" dest="{{HOME_DIR_WEBSERVER}}"
...
