---
- name: Build stage.
  hosts: BUILD
  remote_user: '{{ REMOTE_USER  }}'
  become: yes
  tasks:
  - command: apt update
  - name: Install packages.
    apt: name={{item}} state=present
    with_items: "{{PACKAGES}}"
  - name: GIT clone.
    git: repo='{{GIT_REPO}}' dest='{{GIT_DIR}}'
  - name: Build-app.
    command: chdir='{{GIT_DIR}}' mvn package
  - name: Copy .war file.
    fetch: src="{{PATH_TARGET}}/{{FILE_TARGET}}" dest="/tmp/{{FILE_TARGET}}" flat=true

- name: Prod stage.
  hosts: PROD
  remote_user: '{{ REMOTE_USER  }}'
  become: yes
  tasks:
  - command: apt update
  - name: Install java & tomcat9.
    apt: name={{item}} state=present
    with_items: "{{PACKAGES}}"
  - name: Status tomcat
    service: name=tomcat9 state=started
  - name: Copy .war file.
    copy: src="/tmp/{{FILE_TARGET}}" dest="{{HOME_DIR_WEBSERVER}}"
...
